version: '3.8'

services:
  vm-host:
    build: .
    container_name: level5-vm-host
    privileged: true
    ports:
      - "3005:5000"
      - "5900-5910:5900-5910"
    volumes:
      - /dev/kvm:/dev/kvm
      - vm-data:/app/vms
    devices:
      - /dev/kvm:/dev/kvm
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped

volumes:
  vm-data:
