global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'level-0-process'
    static_configs:
      - targets: ['host.docker.internal:8000']
        labels:
          level: '0'
          type: 'process'

  - job_name: 'level-1-container'
    static_configs:
      - targets: ['level-1-app:3000']
        labels:
          level: '1'
          type: 'container'

  - job_name: 'level-2-compose'
    static_configs:
      - targets: ['level2-api:5000']
        labels:
          level: '2'
          type: 'compose'

  - job_name: 'level-3-kubernetes'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - default
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: level3

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
