# Ruff configuration file
# Ruff is an extremely fast Python linter and formatter, written in Rust
# Documentation: https://docs.astral.sh/ruff/

# Exclude common directories that should not be linted
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Set the maximum line length (same as black default)
line-length = 88

# Indent width (spaces)
indent-width = 4

# Target Python version
target-version = "py310"

[lint]
# Enable specific rule categories
# See https://docs.astral.sh/ruff/rules/ for all available rules
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "ARG",  # flake8-unused-arguments
    "SIM",  # flake8-simplify
    "PTH",  # flake8-use-pathlib
]

# Ignore specific rules
ignore = [
    "E501",  # line-too-long (handled by formatter)
    "E203",  # whitespace-before-punctuation (conflicts with black)
    "W503",  # line-break-before-binary-operator (conflicts with black)
]

# Allow autofix for all enabled rules
fixable = ["ALL"]

# Never try to fix these
unfixable = []

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
# Ignore specific rules in specific files
"__init__.py" = ["F401"]  # Allow unused imports in __init__ files
"tests/*" = ["ARG"]  # Allow unused arguments in tests

[lint.isort]
# Configure isort compatibility
known-first-party = ["{package_name}"]
combine-as-imports = true
force-wrap-aliases = true

[lint.mccabe]
# Maximum McCabe complexity
max-complexity = 10

[lint.pydocstyle]
# Use Google-style docstrings
convention = "google"

[format]
# Enable formatting
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# Format docstrings
docstring-code-format = true
docstring-code-line-length = "dynamic"