version: '3.8'

services:
  api:
    build: ./api
    container_name: level2-api
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - level2-network
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    container_name: level2-redis
    volumes:
      - redis-data:/data
    networks:
      - level2-network
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    container_name: level2-nginx
    ports:
      - "3002:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      - api
    networks:
      - level2-network
    restart: unless-stopped

networks:
  level2-network:
    driver: bridge

volumes:
  redis-data:
